version: '3'

services:
  pico_to_mqtt:
    image: pico_to_mqtt_arm64:latest
    volumes:
      - "./etc-pico-to-mqtt/config:/etc/pico-to-mqtt/config"
      - "./etc-pico-to-mqtt/ssl/cert-${CERT_VERSION:?err}:/etc/pico-to-mqtt/ssl/certs"
      - "./etc-pico-to-mqtt/ssl/root-cert-${ROOT_CERT_VERSION:?err}/etc/pico-to-mqtt/ssl/root-cert"
      - "./etc-pylutron-caseta/ssl/cert-${CASETA_CERT_VERSION:?err}/etc/pylutron-caseta/ssl/certs"
    restart: unless-stopped
    environment:
      - "PICO_TO_MQTT_SETTINGS": "/etc/pico-to-mqtt/config/default-settings.toml:/etc/pico-to-mqtt/config/settings.toml:${cwd}/src/pico_to_mqtt/settings-pi-d-secrets.local.toml"
      - "LOGLEVEL=${PICO_TO_MQTT_LOGLEVEL:INFO}"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
